### PR TITLE
Closes rchurchley/sfuthesis#16 Approval page layout changes

### PR DESCRIPTION
**Pull request by amcpherson**
- modified layout of chair section by adding another minipage
- added some space between the signature line and text
- ragged right for approval page entries, title etc

### CODE REVIEW

**Comment by rchurchley** [comment]
Looks good. Would it be possible to keep the width of `\@approvallabel` and `\@approvalvalue` as `0.4\textwidth` and `0.6\textwidth` respectively? If `\@approvallabel` is shrunk, then the space allotted to the chair no longer fills the remaining width of the page, and committee members' names could misalign with your name, the degree, and title.

**Comment by amcpherson** [comment]
If I understand you correctly then I did this on purpose to match the
example here:
http://www.lib.sfu.ca/sites/default/files/11704/ApprovalPHD5.pdf
(though I think its a little strange myself)

Andrew

**Comment by rchurchley** [comment]
I suppose you're right about the alignment of the examining committee members. In that case, we should remove the `hspace` between members and their signature lines and instead have the `\member` minipage take up `0.5\textwidth`. (This will have the same effect in most cases, but provides a bit of extra room if somebody has a committee member with a very long name.) Similarly, since the Examining Committee box has a width of `0.35\textwidth`, the chair's boxes should be `0.1\textwidth` and `0.55\textwidth` to fill up the available space.

I suppose to make the approval page match the example you linked, we will also have to capitalize the word Chair and un-bold the chair's name.

**Comment by amcpherson** [comment]
Sounds good.  The reason for the hspace was that it looks a bit strange if
a name or description is touching the signature line.  I will leave it to
you.

**Comment by rchurchley** [comment]
> The reason for the hspace was that it looks a bit strange if a name or description is touching the signature line.

It's true that this looks a bit weird, but it also looks weird if a member's name has to be hyphenated or go on to a second line. By enlarging the space, we give the student the ability to decide which option is less bad for their particular situation. After all, it's easy for a user to force a line break, but difficult to enlarge the available space.

Shall I merge this pull request and then make those edits, or would you like to fix them before merging?

**Comment by amcpherson** [comment]
up to you though I might not have time today.

**Pull request merged**
